export const defaultTitle = "JC Lee | Web designer & developer"
export const defaultCardSrc = "/images/card0.png"
export const defaultDescription = "I build the best experience for your users."
export const blogHomeDescription = "I touch on Web development, Design and random insights from my journey into tech."
export const blogTitlePrefix = "JC Lee's Blog | "
